"""foreign key user_id

Revision ID: 91aadeefd67a
Revises: 4b46f0be6fc6
Create Date: 2025-01-30 13:20:44.380891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91aadeefd67a'
down_revision: Union[str, None] = '4b46f0be6fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wishlist', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_column('wishlist', 'user_id')
    # ### end Alembic commands ###
